consul:
  image: progrium/consul
  ports:
    - "8300:8300"
    - "8301:8301/udp"
    - "8302:8302/udp"
    - "8500:8500"
    - "8600:53"
    - "172.17.42.1:53:53/udp"
  dns: 8.8.8.8
  command: -bootstrap-expect 1 -advertise 172.17.42.1 -server -ui-dir /ui
  net: "bridge"

registrator:
  image: progrium/registrator
  dns:
    - 172.17.42.1
    - 8.8.8.8
  entrypoint:
    - "registrator"
    - "-internal"
    - "consul://consul.service.consul:8500"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  net: "bridge"

elasticsearch:
  image: searchspring/elasticsearch:consul-config-1.3.4
  dns:
    - 172.17.42.1
    - 8.8.8.8
  ports:
    - "9200:9200"
  expose:
    - "9200"
  environment:
    - SERVICE_9200_NAME=elk_es
    - SERVICE_TAG=kibana
    - CLUSTERNAME=kibana

kibana:
  build: .
  dns:
    - 172.17.42.1
    - 8.8.8.8
  ports:
    - "5601:5601"
  environment:
    - SERVICE_5601_NAME=kibana
    - SERVICE_TAG=kibana